version: '3.3'

services:
  reth:
    # image: "ghcr.io/bitfinity-network/bitfinity-reth:bitfinity-archive-node"
    image: "bitfinity-archive-node:latest"
    build:
      dockerfile: ./Dockerfile
    ports:
      - '8080:8080'
    command: node -vvv --http --http.port 8080 --http.addr 0.0.0.0 --http.api "debug,eth,net,trace,txpool,web3" --disable-discovery --ipcdisable --no-persist-peers -r https://block-extractor-testnet-1052151659755.europe-west9.run.app -i 10 -b 100 --datadir /reth/data
    volumes:
      - ./target/reth:/reth
