[alias]
docs = "doc --workspace --all-features --no-deps"

[target.x86_64-pc-windows-msvc]
rustflags = [
    # Increases the stack size to 10MB, which is
    # in line with Linux (whereas default for Windows is 1MB)
    "-Clink-arg=/STACK:10000000",
]

[target.i686-pc-windows-msvc]
rustflags = [
    # Increases the stack size to 10MB, which is
    # in line with Linux (whereas default for Windows is 1MB)
    "-Clink-arg=/STACK:10000000",
]


[patch."https://github.com/bitfinity-network/bitfinity-evm-sdk"]
did = { path = "../bitfinity-evm-sdk/src/did" }
eth-signer = { path = "../bitfinity-evm-sdk/src/eth-signer" }
ethereum-json-rpc-client = { path = "../bitfinity-evm-sdk/src/ethereum-json-rpc-client" }
evm-canister-client = { path = "../bitfinity-evm-sdk/src/evm-canister-client" }
signature-verification-canister-client = { path = "../bitfinity-evm-sdk/src/signature-verification-canister-client" }
