name: 'Deploy Bitfinity Reth to GHCR'

on:
  workflow_dispatch: {}

  push:
    branches: [bitfinity-archive-node]
    tags:
      - 'v*'

# Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
permissions:
  contents: read
  packages: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  IMAGE_NAME: bitfinity-reth

jobs:
  deploy-to-ghcr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: gh-meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image to GitHub Container Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.gh-meta.outputs.tags }}

  deploy-to-gcp:
    env:
      GCP_REGISTRY: us-east4-docker.pkg.dev
    runs-on: ubuntu-latest
    needs: deploy-to-ghcr
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GCP Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.GCP_REGISTRY }}
          username: _json_key
          password: ${{ secrets.GCP_ARCHIVER_DEPLOYER }}

      - name: Extract metadata (tags, labels) for Docker
        id: gcp-meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.GCP_REGISTRY }}/dfx-server/reth-bitfinity-repo/${{ env.IMAGE_NAME }}

      - name: Build and push Docker image to GCP Registry
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.gcp-meta.outputs.tags }}
